builds:
  - main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/tf2d2/tf2d2/internal/version.version={{.Version}}
      - -X github.com/tf2d2/tf2d2/internal/version.commit={{.Commit}}
      - -X github.com/tf2d2/tf2d2/internal/version.date={{.CommitDate}}
      - -X github.com/tf2d2/tf2d2/internal/version.builtBy=goreleaser
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

dockers:
- dockerfile: docker/Dockerfile
  image_templates:
  - 'ghcr.io/tf2d2/tf2d2:latest'
  - 'ghcr.io/tf2d2/tf2d2:{{ .RawVersion }}'

brews:
  - tap:
      owner: tf2d2
      name: homebrew-tap
    commit_author:
      name: tf2d2-bot
      email: bot@tf2d2.io
    url_template: "https://github.com/tf2d2/tf2d2/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/tf2d2/"
    description: "Generate D2 diagram from Terraform"
    test: |
      system "#{bin}/tf2d2 version"

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}_SHA256SUMS'

snapshot:
  name_template: "{{ incpatch .Version }}-devel"

# generated by: https://github.com/semantic-release/semantic-release
# changelog:

# The lines beneath this are called `modelines`. See `:help modeline`
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
