preset: conventionalcommits
branches:
- main
ci: false
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
    changelogTitle: |-
      # Changelog

      All notable changes to this project will be documented in this file.
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
    message: |-
      chore(release): version ${nextRelease.version} [skip ci]
- - "@semantic-release/exec"
  - publishCmd: |-
      echo "${nextRelease.notes}" > /tmp/release-notes.md
