name: Report Bug
description: Report a bug causing unexpected behaviour.
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for reporting a bug! :+1:

        Before submitting a bug report, please check for existing issues that may report the same issue to keep all relevant information in one place.

  - type: input
    id: version
    attributes:
      label: tf2d2 Version
      description: The semantic version of `tf2d2` used when experiencing the bug. If multiple versions have been tested, a comma separated list.
      placeholder: "X.Y.Z"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Description of what should have happened.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error/Panic Output Snippet
      description: |
        If relevant, provide a snippet of the error/panic output. This will be rendered with `shell` syntaxt highlighting, do not use [code fences](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
      render: Shell
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Configuration and Logging

        If appropriate, provide the `tf2d2` configuration and, when possible, the debug logs. For configurations or logs of more than just a few lines, it's preferred to either share a Gist link or zip the files and upload them.

        Debug logs under 25MB may be [attached directly in the field](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files). Files larger than this should be uploaded to a file hosting service and a link shared.

        **Note:** The form fields below do not automatically render, so you will need to use [code fence(s)](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to achieve proper formatting.

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: List of steps to reproduce the bug.
      placeholder: |
        1. `tf2d2 ...`
    validations:
      required: true

  - type: textarea
    id: debug_logs
    attributes:
      label: Debug Output
      description: |
        If possible, please paste, upload, or link to a file or Gist containing debug logs. See note above for additional information on file size restrictions and encrypting.

        To obtain the debug output, use the `-v` flag to enable verbose output.
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Additional details such as links to any other relevant documentation, other GitHub issues and/or pull requests.

        [How to reference Github Issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)
    validations:
      required: false
